name: Publishing Package
on: [push]
jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      - run: python -m setup build sdist
          
        
  upload-pypi-project:
    runs-on: ubuntu-latest
    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.5.0
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
