# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint Python Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    lint-python-application:
      runs-on: ubuntu-latest
      steps:
        - name: Python Linter
        # You may pin to the exact commit or the version.
        # uses: sunnysid3up/python-linter@93076bd8f740f062069291d738fc70c1b4171c1d
          uses: sunnysid3up/python-linter@v0.1-beta.7
